hydra:
    run:
        dir: .
# general
batch_size: 6
num_workers: 6
num_epochs: 200
device: cuda:0
save_path: models
experiment_name: test
seed: 21
# data
data_path: PATH_HERE
# training
early_stopping: 50
learning_rate: 1e-3
weight_decay: 1e-4
lr_factor: 0.5
lr_patience: 10